version: '3.8'
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server
  orderdb:
    image: mcr.microsoft.com/mssql/server
  rabbitmq:
    image: rabbitmq:3.8.14-management
volumes:
  catologdb_volume:
  discountdb_volume:
  orderdb_volume:
  identitydb_volume:

    